version: '3'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: eBoutiqueSymphony
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - eboutiquesymphony_database_data2:/var/lib/mysql
    ports:
      - 3307:3306
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  app:
    build: .
    ports:
      - 8000:80
    depends_on:
      - database
    volumes:
      - .:/var/www/html

volumes:
###> doctrine/doctrine-bundle ###
  eboutiquesymphony_database_data2:
###< doctrine/doctrine-bundle ###
